### ISSUE TITLE
[Feature Request] Adding New Templates

### ISSUE THREAD

**Issue by andrewdmaclean** [peterpeterparker/tietracker#86]
Hey @peterpeterparker making this more official with a template feature request.
---
### 1️⃣ Is your feature request related to a problem? Please describe.
I am often needing to change the template descriptions after the time has been recorded as I am not in a Software Development role.

### 2️⃣ Describe the solution you'd like
I would like to be able to add, remove and edit the templates provided in the app.

### 3️⃣ Describe alternatives you've considered
I have attempted to change the descriptions after submission but am running into issues with the Update Button not working (see #87).

### 4️⃣ Additional context
_Original Message Below_
> Hey @peterpeterparker 👋
> 
> Love the app, but wondering about the ability to create/edit template titles - should this be possible?
> 
> Thanks for your amazing work!

**Comment by peterpeterparker** [comment]
Hi @andrewdmaclean 👋

Thank you for the feedback.

What do you mean with "create/edit template titles" ? Do you mean the "tasks  templates" (see screenshot) ?

<img width="763" alt="Capture d’écran 2020-11-03 à 17 24 12" src="https://user-images.githubusercontent.com/16886711/98012480-70b67500-1df9-11eb-9f7d-3376eb646c88.png">

**Comment by andrewdmaclean** [comment]
Wow! Now that is fast response time 🏃🏼‍♂️

Yes, the task templates are what I am referencing.

I know that you can edit the descriptions in the diary directly, but I am having trouble updating changes to the descriptions in the iOS app, and wondered if the task templates themselves could be updated?

I realize the app is built with developers in mind, but wanted to check in.

**Comment by peterpeterparker** [comment]
Thank you for your fast feedback too 🏃🏼‍♂️😉

Originally I was thinking on making the templates editable but to gain time and also because I was not sure on which components I should use to do so, I decided to not implement such feature 😅.

Of course I'll be happy to improve the app. I think, spontaneously, that technically is would not be a breaking changes, so that's a good point.

Have you  any inputs regarding UX/design/components?

I like  the current component as it allow to change  the order of the templates, it would nice to keep it.

Thinking out at loud: It probably needs a new modal in  which it is possible to either "edit / delete / add" a template or these operations can be performed in the main page and the modal can be use to "re-order" the templates...

Looking forward to your ideas.

**Comment by andrewdmaclean** [comment]
@peterpeterparker so far I am finding the UX pretty good, except I am having intermittent trouble with updating Diary Entries.

For some reason, it seems that I am only about to "Update" a particular entry if I change the "From" date to exactly 1 day before - is this a bug?

Additionally, it would be great to be able to delete Clients as well.

**Comment by peterpeterparker** [comment]
thx @andrewdmaclean ! I was more looking for a feedback on this particular request / feature but happy to get to know more too 😉

- I don't face the "1 day before" issue but doesn't mean it does not exist. I use Android so it can be a OS specific issue. might be worth to open an issue in case someone can related too (-> #87)

- deleting clients would be a bit tricky or I would rather not. I kind of think that once a client has been billed, the entries should not be deleted but, don't know if  you know this, it is possible to discontinue ("mark as inactive") a project. doing so it will not appear anymore in the list  of selectable projects.

**Comment by peterpeterparker** [comment]
I began to develop this one  this evening, the design and UX are now cleared I think.
Kind of busy next days, I'll do my best.

<img width="710" alt="Capture d’écran 2020-11-03 à 21 37 07" src="https://user-images.githubusercontent.com/16886711/98038230-10d1c580-1e1d-11eb-9212-3e116af754f3.png">

<img width="710" alt="Capture d’écran 2020-11-03 à 21 37 11" src="https://user-images.githubusercontent.com/16886711/98038232-1202f280-1e1d-11eb-8278-770b822b7411.png">

<img width="710" alt="Capture d’écran 2020-11-03 à 21 37 03" src="https://user-images.githubusercontent.com/16886711/98038215-0ca5a800-1e1d-11eb-8eb6-730f213679ef.png">

**Comment by peterpeterparker** [comment]
@andrewdmaclean this has been developed and deploy in the PWA (not yet in store, will be shipped in v1.5.0). 

can you please give a try in an incognito browser to https://tietracker.com in order to check if the solution to edit, delete and add templates suit your need?

if not, obviously I'll be happy to reopen the issue and make the changes you would need.

looking forward to your feedback.

thank you for the great idea 👍

**Comment by andrewdmaclean** [comment]
@peterpeterparker the UX is awesome :) Thank you so much!

**Comment by peterpeterparker** [comment]
awesome, happy to hear that! thx for the feedback
